export const FETCH_BOOKS = 'FETCH_BOOKS';

export const FETCH_BOOK = 'FETCH_BOOK';


export const UPDATE_PAGENATION = 'UPDATE_PAGENATION';

export const ASYNC_ACTION_START = 'ASYNC_ACTION_START';
export const ASYNC_ACTION_FINISH = 'ASYNC_ACTION_FINISH';
export const ASYNC_ACTION_ERROR = 'ASYNC_ACTION_ERROR';